### PR TITLE
Issue#27

### LINKED ISSUE #27: Aggregator App: Inconsistent return behaviour and noncompliance to the documentation
From @SafaArooj:

The documentation states, that by default aggregator app returns a collection of payloads and we don’t need to provide any `aggregation` expression if that’s what we want. But while working with it I have observed a discrepancy. Although it does return a list but the elements of list are either object addresses or some sort of transformed byte arrays.

For example: If I provide no `aggregation` expression the returned list looks something (Data sent to http using Postman)
`["ew0KCSJwYXlsb2FkIjogew0KCQkiU09VUkNFX1RBQkxFIjogIklOVk9JQ0VfQUREUkVTUyIsDQoJCSJWRU5ET1JfTkJSIjogODQxMjk1MCwNCgkJIklOVk9JQ0VfSUQiOiAxMjc2NTEzMjYsDQoJCSJJTlZfQUREUl9UWVBFX0NPREUiOiAiUkUiDQoJfQ0KfQ==","ew0KCSJwYXlsb2FkIjogew0KCQkiU09VUkNFX1RBQkxFIjogIklOVk9JQ0VfQUREUkVTUyIsDQoJCSJJTlZPSUNFX0lEIjogMTI3NjUxMzI2DQoJfQ0KfQ=="]`

But If I provide `#this.![new String(payload)]`, the returned list is:

`["{\r\n\t\"payload\": {\r\n\t\t\"SOURCE_TABLE\": \"INVOICE\",\r\n\t\t\"INVOICE_ID\": 127651326\r\n\t}\r\n}","{\r\n\t\"payload\": {\r\n\t\t\"SOURCE_TABLE\": \"INVOICE_ADDRESS\",\r\n\t\t\"INVOICE_ID\": 127651326\r\n\t}\r\n}"]`

Which is a list of strings with actual message. 

However if I use dataflow server shell to post messages to the http channel (when no aggregate expression is provided), it prints out the object addresses as following:

`[[B@59418842, [B@76d9b1a]`

Although providing the above mentioned aggregate expression resolves this issue but before that I looked into the code and modifying the `DefaultAggregatingMessageGroupProcessor` worked for me as well. I changed the code to following:

```
for (Message<?> message : messages) {
    if (message.getPayload() instanceof byte[]) {
        String contentType = message.getHeaders().containsKey(MessageHeaders.CONTENT_TYPE)
                ? message.getHeaders().get(MessageHeaders.CONTENT_TYPE).toString()
                : BindingProperties.DEFAULT_CONTENT_TYPE.toString();
        if (contentType.contains("text") || contentType.contains("json") || contentType.contains("x-spring-tuple")) {
            message = new MutableMessage<>(new String(((byte[]) message.getPayload())), message.getHeaders());
        }
        payloads.add(message.getPayload());
    }
}
```

The above returns a list of actual messages without providing any aggregate expression as opposed to the actual aggregator app. The DSL I used with my custom app is the following:

`http --server.port=8074 | aggApp --aggregator.release='size() == 2' --aggregator.correlation=#jsonPath(payload,'payload.INVOICE_ID') | log`

The version I am using is “2.1.0.RELEASE”. If you believe that this is not a bug but an intended behavior of the app then can you please at least update the documentation to use `#this.![new String(payload)]' aggregate expression for the retrieval of actual messages. Because for a SpEL and a spring cloud data flow novice like me it was extremely frustrating to figure this thing out.

> Logs

# Data returned by the actual aggregator app:

```
 _Source : Data flow server shell_
`2019-06-06 17:36:22.006  INFO 18136 --- [container-0-C-1] log-sink                                 : [[B@771453a9, [B@2e2c8d1e]
_Source : Postman_
2019-06-06 17:36:58.817  INFO 18136 --- [container-0-C-1] log-sink                                 : ["ew0KCSJwYXlsb2FkIjogew0KCQkiU09VUkNFX1RBQkxFIjogIklOVk9JQ0VfQUREUkVTUyIsDQoJCSJJTlZPSUNFX0lEIjogMTI3NjUxMzI2DQoJfQ0KfQ==","ew0KCSJwYXlsb2FkIjogew0KCQkiU09VUkNFX1RBQkxFIjogIklOVk9JQ0UiLA0KCQkiSU5WT0lDRV9JRCI6IDEyNzY1MTMyNg0KCX0NCn0="]
```
# Data returned by the modified aggregator app:
 ```
_Source : Data flow server shell_
2019-06-06 17:39:25.698  INFO 6596 --- [container-0-C-1] log-sink                                 : [{"payload":{"SOURCE_TABLE":"INVOICE","INVOICE_ID":127651326}}, {"payload":{"SOURCE_TABLE":"INVOICE_ADDRESS","INVOICE_ID":127651326}}]
_Source : Postman_
2019-06-06 17:39:37.280  INFO 6596 --- [container-0-C-1] log-sink                                 : ["{\r\n\t\"payload\": {\r\n\t\t\"SOURCE_TABLE\": \"INVOICE_ADDRESS\",\r\n\t\t\"INVOICE_ID\": 127651326\r\n\t}\r\n}","{\r\n\t\"payload\": {\r\n\t\t\"SOURCE_TABLE\": \"INVOICE\",\r\n\t\t\"INVOICE_ID\": 127651326\r\n\t}\r\n}"]
```

### PR DESCRIPTION
**Pull request by SafaArooj**
Instead of directly transforming data of type Message<?>, I've transform/alter it using MutalbeMessage<?>. MutableMessage<?> has overridden the toString() method which explicitly checks that if payload is of type byte[] and then converts it accordingly. 

Resolves #27.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@SafaArooj Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-stream-app-starters/aggregator&pullRequestId=28)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-stream-app-starters/aggregator&pullRequestId=28) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@SafaArooj Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-stream-app-starters/aggregator&pullRequestId=28)!

**Review by artembilan — CHANGES_REQUESTED** [review]
> `MutableMessage<?>` has overridden the `toString()` method which explicitly checks that if payload is of type `byte[]` and then converts it accordingly.

That's something wrong, you have just misunderstood the code over there:
```
if (this.payload instanceof byte[]) {
	sb.append("byte[").append(((byte[]) this.payload).length).append("]");
}
```
So, there no any conversion - just a `length` of that `byte[]`. 

What am I missing, please?

**Comment by SafaArooj** [comment]
Basically the line of code that decodes the payload back to string is the following:
`message = new MutableMessage<>(new String(((byte[]) message.getPayload())), message.getHeaders());`
Since, in order to convert Byte array into String format correctly, we have to explicitly create a String object and assign the Byte array to it. MutalbeMessage provides a simpler way of modifying the existing Message object instead of creating a new one.

**Comment by artembilan** [comment]
> MutalbeMessage provides a simpler way of modifying the existing Message object instead of creating a new one.

That's not correct, because yo definitely do `new MutableMessage`, so you, essentially, create a new object and return it.

I'm not sure why do we talk about this matter? How is it related to the problem we would like to fix?

Remember my comment in the issue: https://github.com/spring-cloud-stream-app-starters/aggregator/issues/27#issuecomment-501019544 ?

Why your comment is not about a particular fix in this app, but about something like `MutableMessage`?

Please, also take a look into this article: https://chris.beams.io/posts/git-commit/. Your commit messages don't reflect reality and don't follow what we have talked about in the issue.

Thanks for understanding.

**Comment by SafaArooj** [comment]
I think I have not been able to communicate myself clearly. The issue that we are talking about is the inability of aggregator app to return a list of strings without the use of `#this.![new String(payload)]` aggregate expression. As I mentioned previously that without the use of above expression it returns a list of byte arrays. 
Why I think the above works is because we create a new String object by explicitly passing it the byte array of payload object.
I have tried to map the exact same thing in code through the following line:
`message = new MutableMessage<>(new String(((byte[]) message.getPayload())), message.getHeaders());`

> That's not correct, because yo definitely do new MutableMessage, so you, essentially, create a new object and return it.

We create a new object of MutableMessage (implements Message) type and assign it to the same Message object which is of type `Message` which is an interface and therefore cannot be directly instantiated.  Nevertheless, I understand your concerns and I will close the PR myself. Once again thank you so much for your detailed replies.

**Pull request closed without merging**
